# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- development

pool: 
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: 'pwd && ls'
      displayName: 'dotnet build $(buildConfiguration)'
    - script: 'dotnet build'
      displayName: 'dotnet build $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: |
          pipelines-dotnet-core.csproj 
    - task: DotNetCoreCLI@2
      inputs:
        command: 'push'
        searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/*.Tests.nupkg'
        feedPublish: 'FabrikamFeed'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/*.csproj'
        arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
        zipAfterPublish: true
        modifyOutputPath: true
        
          
